"""initial schema - all 11 tables

Revision ID: 384f4a2339a1
Revises: 
Create Date: 2026-07-02 15:47:51.263105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '384f4a2339a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_test_catalog',
    sa.Column('test_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('test_code', sa.String(length=20), nullable=False),
    sa.Column('test_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('sample_type', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('reference_range', sa.String(length=100), nullable=True),
    sa.Column('normal_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('normal_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('default_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('test_id'),
    sa.UniqueConstraint('test_code')
    )
    op.create_table('medicines',
    sa.Column('medicine_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('medicine_name', sa.String(length=100), nullable=False),
    sa.Column('generic_name', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('dosage_form', sa.String(length=50), nullable=True),
    sa.Column('strength', sa.String(length=50), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('medicine_id')
    )
    op.create_table('patients',
    sa.Column('patient_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('patient_number', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('blood_group', sa.String(length=5), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=15), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('medical_history', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('patient_id'),
    sa.UniqueConstraint('patient_number')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('employee_code', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('license_number', sa.String(length=60), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_code'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('inventory',
    sa.Column('inventory_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('medicine_id', sa.BigInteger(), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantity_in_stock', sa.Integer(), nullable=True),
    sa.Column('minimum_stock', sa.Integer(), nullable=True),
    sa.Column('supplier', sa.String(length=100), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.medicine_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inventory_id')
    )
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_index('idx_inventory_medicine', ['medicine_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_role_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_by', sa.BigInteger(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_role_id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_table('visits',
    sa.Column('visit_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('doctor_id', sa.BigInteger(), nullable=False),
    sa.Column('visit_type', sa.String(length=20), nullable=True),
    sa.Column('visit_status', sa.String(length=20), nullable=True),
    sa.Column('visit_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('admission_date', sa.DateTime(), nullable=True),
    sa.Column('discharge_date', sa.DateTime(), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment_plan', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('height', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('blood_pressure', sa.String(length=20), nullable=True),
    sa.Column('pulse_rate', sa.Integer(), nullable=True),
    sa.Column('oxygen_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('visit_id')
    )
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.create_index('idx_visit_doctor', ['doctor_id'], unique=False)
        batch_op.create_index('idx_visit_patient', ['patient_id'], unique=False)

    op.create_table('doctor_report',
    sa.Column('doctor_report_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('visit_id', sa.BigInteger(), nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('doctor_id', sa.BigInteger(), nullable=False),
    sa.Column('report_number', sa.String(length=30), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('clinical_findings', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment_plan', sa.Text(), nullable=True),
    sa.Column('prescribed_medicines', sa.Text(), nullable=True),
    sa.Column('doctor_notes', sa.Text(), nullable=True),
    sa.Column('follow_up_required', sa.Boolean(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('next_visit_reason', sa.Text(), nullable=True),
    sa.Column('report_file', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.visit_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doctor_report_id'),
    sa.UniqueConstraint('report_number')
    )
    with op.batch_alter_table('doctor_report', schema=None) as batch_op:
        batch_op.create_index('idx_doctor_report_doctor', ['doctor_id'], unique=False)
        batch_op.create_index('idx_doctor_report_patient', ['patient_id'], unique=False)
        batch_op.create_index('idx_doctor_report_visit', ['visit_id'], unique=False)

    op.create_table('inventory_transactions',
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('inventory_id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=30), nullable=True),
    sa.Column('reference_id', sa.BigInteger(), nullable=True),
    sa.Column('performed_by', sa.BigInteger(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.inventory_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.create_index('idx_inventory_txn', ['inventory_id'], unique=False)

    op.create_table('laboratory',
    sa.Column('lab_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('visit_id', sa.BigInteger(), nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('requested_by', sa.BigInteger(), nullable=False),
    sa.Column('lab_technician_id', sa.BigInteger(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('sample_type', sa.String(length=50), nullable=True),
    sa.Column('sample_collected_at', sa.DateTime(), nullable=True),
    sa.Column('test_status', sa.String(length=30), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lab_technician_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.visit_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lab_id')
    )
    with op.batch_alter_table('laboratory', schema=None) as batch_op:
        batch_op.create_index('idx_lab_patient', ['patient_id'], unique=False)
        batch_op.create_index('idx_lab_requested_by', ['requested_by'], unique=False)
        batch_op.create_index('idx_lab_status', ['test_status'], unique=False)
        batch_op.create_index('idx_lab_visit', ['visit_id'], unique=False)

    op.create_table('prescriptions',
    sa.Column('prescription_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('visit_id', sa.BigInteger(), nullable=False),
    sa.Column('inventory_id', sa.BigInteger(), nullable=False),
    sa.Column('prescribed_by', sa.BigInteger(), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.inventory_id'], ),
    sa.ForeignKeyConstraint(['prescribed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.visit_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prescription_id')
    )
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index('idx_prescription_visit', ['visit_id'], unique=False)

    op.create_table('lab_report',
    sa.Column('lab_report_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lab_id', sa.BigInteger(), nullable=False),
    sa.Column('test_id', sa.BigInteger(), nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('doctor_id', sa.BigInteger(), nullable=False),
    sa.Column('report_number', sa.String(length=30), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('reference_range', sa.String(length=100), nullable=True),
    sa.Column('is_abnormal', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.BigInteger(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('report_file', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['lab_id'], ['laboratory.lab_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['lab_test_catalog.test_id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('lab_report_id'),
    sa.UniqueConstraint('report_number')
    )
    with op.batch_alter_table('lab_report', schema=None) as batch_op:
        batch_op.create_index('idx_lab_report_doctor', ['doctor_id'], unique=False)
        batch_op.create_index('idx_lab_report_lab', ['lab_id'], unique=False)
        batch_op.create_index('idx_lab_report_patient', ['patient_id'], unique=False)
        batch_op.create_index('idx_lab_report_test', ['test_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_report', schema=None) as batch_op:
        batch_op.drop_index('idx_lab_report_test')
        batch_op.drop_index('idx_lab_report_patient')
        batch_op.drop_index('idx_lab_report_lab')
        batch_op.drop_index('idx_lab_report_doctor')

    op.drop_table('lab_report')
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index('idx_prescription_visit')

    op.drop_table('prescriptions')
    with op.batch_alter_table('laboratory', schema=None) as batch_op:
        batch_op.drop_index('idx_lab_visit')
        batch_op.drop_index('idx_lab_status')
        batch_op.drop_index('idx_lab_requested_by')
        batch_op.drop_index('idx_lab_patient')

    op.drop_table('laboratory')
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.drop_index('idx_inventory_txn')

    op.drop_table('inventory_transactions')
    with op.batch_alter_table('doctor_report', schema=None) as batch_op:
        batch_op.drop_index('idx_doctor_report_visit')
        batch_op.drop_index('idx_doctor_report_patient')
        batch_op.drop_index('idx_doctor_report_doctor')

    op.drop_table('doctor_report')
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index('idx_visit_patient')
        batch_op.drop_index('idx_visit_doctor')

    op.drop_table('visits')
    op.drop_table('user_roles')
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index('idx_inventory_medicine')

    op.drop_table('inventory')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('patients')
    op.drop_table('medicines')
    op.drop_table('lab_test_catalog')
    # ### end Alembic commands ###
